In [ ]:
# import numpy as np

# X = np.array([1.0, -2.0], dtype=np.float64)
# TARGET_CLASS = 1

# W1 = np.array([
#     [0.50, -0.50],
#     [1.00, 0.25],
#     [-0.75, -0.50]
# ], dtype=np.float64)

# B1 = np.array([0.0, 0.5, -0.25], dtype=np.float64)

# W2 = np.array([
#     [0.4, -0.6, 0.5],
#     [-0.2, 0.8, -0.3]
# ], dtype=np.float64)

# B2 = np.array([0.1, -0.1], dtype=np.float64)

In [ ]:
# def networkRepresentation():
#     return{
#         "input_neurons":len(X),
#         "hidden_neurons":W1.shape[0],
#         "output_neurons":W2.shape[0],
#         "parameter_count":W1.size + B1.size + W2.size + B2.size
        
#     }

# def hiddenForward():
#     z1 = np.dot(W1,X)+B1
#     a1 = np.maximum(0,z1)
#     return np.round(z1,4),np.round(a1,4)

# def outputForward():
#     _,a1 = hiddenForward()
#     logits = np.dot(W2,a1)+B2
#     shifts = logits - np.max(logits)
#     probs = np.exp(shifts)
#     probs = probs/np.sum(probs)
#     aa = np.round(logits,3).tolist(),
#     bb=np.round(probs,4).tolist(),
#     return aa ,bb


# def predictionSummary():
#     _,probs = outputForward()
#     predicted = int(np.argmax(probs))
#     loss = float(-np.log(probs[TARGET_CLASS]))
#     return np.round(probs,4),predicted,round(loss,4)

In [ ]:
# hiddenForward()
# networkRepresentation()
# outputForward()

(([0.1, 0.4],), ([0.4256, 0.5744],))

In [ ]:
# import numpy as np

# X = np.array([1.0, -1.0], dtype=np.float64)
# Y = 1.0
# LEARNING_RATE = 0.1

# W1 = np.array([
#     [0.4, -0.2],
#     [0.1, 0.3]
# ], dtype=np.float64)

# B1 = np.array([0.0, 0.0], dtype=np.float64)

# W2 = np.array([0.7, -0.5], dtype=np.float64)

# B2 = 0.0



# def networkRepresentation():
#     return{
#         "input_neurons":len(X),
#         "hidden_neurons":W1.shape[0],
#         "output_neurons":W2.shape[0],
#         "perameter_count":W1.size + W2.size + B1.size +1
#     }

# def forwardPass():
#     z1 = np.dot(W1,X)+B1
#     a1 = np.tanh(z1)
#     z2 = np.dot(W2,a1)+B2
#     prediction = 1/(1+np.exp(-z2))
#     loss =-(Y*np.log(prediction)+(1-Y)*np.log(1-prediction))
#     return(
#         np.round(z1,4),
#         np.round(a1,4),
#         float(np.round(z2,4)),
#         float(np.round(prediction,4)),
#         float(np.round(loss,4))
#     )

# def backwardPass():
#     z1 = np.dot(W1,X)+B1
#     a1 = np.tanh(z1)
#     z2 = np.dot(W2,a1)+B2
#     prediction = 1/(1+np.exp(-z2))
#     dz2 = prediction-Y
#     dW2 = dz2*a1
#     db2 = dz2
#     da1 = W2*dz2
#     dz1 = da1 * (1-a1**2)
#     dW1 = np.outer(dz1,X)
#     db1 = dz1

#     return(
#         np.round(dW1,4),
#         np.round(db1,4),
#         np.round(dW2,4),
#         float(np.round(db2,4))
#     )


# def trainOneStep():
#     z1,a1,z2,prediction,loss_before=forwardPass()
#     dW1,db1,dW2,db2 =backwardPass()

#     W1_new = W1-LEARNING_RATE*dW1
#     W2_new = W2-LEARNING_RATE*dW2
#     B1_new=B1-LEARNING_RATE*db1
#     B2_new=B2-LEARNING_RATE*db2

#     z1 = np.dot(W1_new,X)+B1_new
#     a1 = np.tanh(z1)
#     z2 = np.dot(W2_new,a1)+B2_new
#     prediction = 1/(1+np.exp(-z2))
#     loss_after = -(Y*np.log(prediction)+(1-Y)*np.log(1-prediction))
#     return float(np.round(loss_before,4)) ,float(np.round(loss_after,4))

In [ ]:
# forwardPass()

(array([ 0.6, -0.2]), array([ 0.537 , -0.1974]), 0.4746, 0.6165, 0.4837)

In [ ]:
# import numpy as np

# X = np.array([
#     [1.0, 0.0],
#     [0.0, 1.0],
#     [1.0, 1.0],
#     [-1.0, 1.0]
# ], dtype=np.float64)

# Y = np.array([1.0, 0.0, 1.0, 0.0], dtype=np.float64)

# INITIAL_WEIGHTS = np.array([0.0, 0.0], dtype=np.float64)
# INITIAL_BIAS = 0.0
# LEARNING_RATE = 0.1

# STOCHASTIC_INDEX = 0
# MINI_BATCH_INDICES = [0, 1]



# def fullBatchUpdate():
#     pred = np.full(len(Y),0.5)
#     error = pred-Y
#     grad_w = np.mean(error[:,None]*X,axis=0)
#     grad_b = np.mean(error)
#     updated_w = INITIAL_WEIGHTS - LEARNING_RATE*grad_w
#     updated_b = INITIAL_BIAS -LEARNING_RATE*grad_b

#     # return{
#     #     "grad_w":np.round(grad_w,4).tolist(),
#     #     "grad_b":float(np.round(grad_b,4)),
#     #     "updated_w":np.round(updated_w,4).tolist(),
#     #     "updated_b":float(np.round(updated_b,4))
#     # }
#     return(
#         np.round(grad_w,4).tolist(),
#         float(np.round(grad_b,4)),
#         np.round(updated_w,4).tolist(),
#         float(np.round(updated_b,4))
#     )

# def stochasticUpdate():
#     x = X[STOCHASTIC_INDEX]
#     y = Y[STOCHASTIC_INDEX]
#     pred = 0.5
#     error = pred-y
#     grad_w = error*x
#     grad_b = error
#     updated_w = INITIAL_WEIGHTS-LEARNING_RATE*grad_w
#     updated_b = INITIAL_BIAS - LEARNING_RATE*grad_b
#     return {
#         "grad_w":np.round(grad_w,4).tolist(),
#         "grad_b":float(np.round(grad_b,4)),
#         "updated_w":np.round(updated_w,4).tolist(),
#         "updated_b":float(np.round(updated_b,4))
#     }

# def miniBatchUpdate():
#     x = X[MINI_BATCH_INDICES]
#     y = Y[MINI_BATCH_INDICES]
#     pred = np.full(len(x),0.5)
#     error = pred-y
#     grad_w = np.mean(error[:,None]*x,axis=0)
#     grad_b = np.mean(error)
#     updated_w = INITIAL_WEIGHTS-LEARNING_RATE*grad_w
#     updated_b = INITIAL_BIAS - LEARNING_RATE*grad_b
#     return {
#         "grad_w":np.round(grad_w,4).tolist(),
#         "grad_b":float(np.round(grad_b,4)),
#         "updated_w":np.round(updated_w,4).tolist(),
#         "updated_b":float(np.round(updated_b,4))
#         }

# def compareVariants():
#     _,_,full_w,full_b = fullBatchUpdate()
#     _,_,sgd_w,sgd_b = stochasticUpdate()
#     _,_,mbg_w,mbg_b = miniBatchUpdate()
#     return(
#         (full_w,full_b),
#         (sgd_w,sgd_b),
#         (mbg_w,mbg_b)
#     )


In [ ]:
# fullBatchUpdate()
# stochasticUpdate()
# miniBatchUpdate()
# compareVariants()

([-0.375, 0.125], 0.0, [0.0375, -0.0125], 0.0)

In [ ]:
# import numpy as np

# X = np.array([1.5, -0.5], dtype=np.float64)
# Y = np.array([1.0, 0.0], dtype=np.float64)
# LEARNING_RATE = 0.1

# W = np.array([
#     [0.2, -0.4],
#     [0.7,  0.1]
# ], dtype=np.float64)

# B = np.array([0.1, -0.2], dtype=np.float64)

# def forwardDense():
#     z = np.dot(W,X)+B
#     prediction = 1/(1+np.exp(-z))
#     return np.round(z,4).tolist() , np.round(prediction,4).tolist()

# def calculateDenseLoss():
#     z,prediction=forwardDense()
#     prediction =np.array(prediction)
#     loss =-np.mean(Y*np.log(prediction)+(1-Y)*np.log(1-prediction))
#     return float(np.round(loss,4))

# def backwardDense():
#     z = np.dot(W,X)+B
#     prediction = 1/(1+np.exp(-z))

#     dz = (prediction-Y)/len(Y)
#     dw = np.outer(dz,X)
#     db = dz
#     return(
#         np.round(dw,4).tolist(),
#         db.tolist()
#     )

# def trainDenseOneStep():
#     z = np.dot(W,X)+B
#     prediction = 1/(1+np.exp(-z))
#     loss_before = -np.mean(Y*np.log(prediction)+(1-Y)*np.log(1-prediction))

#     dz = (prediction-Y)/len(Y)
#     dw = np.outer(dz,X)
#     db = dz

#     updated_W = W-LEARNING_RATE*dw

#     updated_B = B-LEARNING_RATE*db

#     z_new = np.dot(updated_W,X)+updated_B

#     pred_new = 1/(1+np.exp(-z_new))
#     loss_after = -np.mean(Y*np.log(pred_new)+(1-Y)*np.log(1-pred_new))

#     return float(np.round(loss_before,4)) , float(np.round(loss_after,4))


In [189]:
# forwardDense()
# calculateDenseLoss()
# backwardDense()
# trainDenseOneStep()

In [ ]:
# import numpy as np

# TOKEN_EMBEDDINGS = np.array([
#     [0.1,  0.2, 0.3,  0.4],
#     [0.5,  0.4, 0.3,  0.2],
#     [0.0, -0.1, 0.2, -0.2]
# ], dtype=np.float64)

# POSITIONAL_ENCODINGS = np.array([
#     [0.0, 1.0, 0.0, 1.0],
#     [0.5, 0.5, 0.5, 0.5],
#     [1.0, 0.0, 1.0, 0.0]
# ], dtype=np.float64)

# D_MODEL = 4


# def transformerDimensions():
#     sequence_length = TOKEN_EMBEDDINGS.shape[0]
#     embedding_dimension = TOKEN_EMBEDDINGS.shape[1]
#     scale_factor = np.sqrt(D_MODEL)
#     return(
#         sequence_length,
#         embedding_dimension,
#         float(np.round(scale_factor,4))
#     )

# def scaleTokenEmbeddings():
#     scaled = TOKEN_EMBEDDINGS*np.sqrt(D_MODEL)
#     return np.round(scaled,4).tolist()

# def addPositionalEncoding():
#     scaled = scaleTokenEmbeddings()
#     encoded = scaled+POSITIONAL_ENCODINGS
#     return np.round(encoded,4).tolist()

# def transformerInputSummary():
#     encoded = addPositionalEncoding()
#     # encoded = np.array(encoded)
#     sequence_mean = np.mean(encoded,axis=0)
#     return(
#         np.round(encoded,4).tolist(),
#         np.round(sequence_mean,4).tolist()
#     )

In [ ]:
# transformerDimensions()
# scaleTokenEmbeddings()
# addPositionalEncoding()
# transformerInputSummary()

([[0.2, 1.4, 0.6, 1.8], [1.5, 1.3, 1.1, 0.9], [1.0, -0.2, 1.4, -0.4]],
 [0.9, 0.8333, 1.0333, 0.7667])

In [ ]:
# import numpy as np

# X = np.array([
#     [1.0,0.0],
#     [0.0,1.0],
#     [1.0,1.0]
# ], dtype=np.float64)

# WQ = np.array([
#     [1.0,0.0],
#     [0.0,1.0]
# ], dtype=np.float64)

# WK = np.array([
#     [1.0,1.0],
#     [0.0,1.0]
# ], dtype=np.float64)

# WV = np.array([
#     [1.0,0.5],
#     [-0.5,1.0]
# ], dtype=np.float64)

# D_K = 2


# # ---------------- Concept 1 ----------------
# def projectQKV():

#     Q = np.dot(X,WQ)
#     K = np.dot(X,WK)
#     V = np.dot(X,WV)

#     return (
#         np.round(Q,4),
#         np.round(K,4),
#         np.round(V,4)
#     )


# # ---------------- Concept 2 ----------------
# def calculateAttentionScores():

#     Q,K,_ = projectQKV()

#     scores = np.dot(Q,K.T)/np.sqrt(D_K)

#     return np.round(scores,4)


# # ---------------- Concept 3 ----------------
# def calculateAttentionWeights():

#     Q = np.dot(X,WQ)
#     K = np.dot(X,WK)

#     scores = np.dot(Q,K.T)/np.sqrt(D_K)

#     # Stable Softmax
#     scores = scores - np.max(scores,axis=1,keepdims=True)

#     exp_scores = np.exp(scores)

#     weights = exp_scores/np.sum(exp_scores,axis=1,keepdims=True)

#     return np.round(weights,4)


# # ---------------- Concept 4 ----------------
# def selfAttentionOutput():

#     Q = np.dot(X,WQ)
#     K = np.dot(X,WK)
#     V = np.dot(X,WV)

#     scores = np.dot(Q,K.T)/np.sqrt(D_K)

#     scores = scores - np.max(scores,axis=1,keepdims=True)

#     exp_scores = np.exp(scores)

#     weights = exp_scores/np.sum(exp_scores,axis=1,keepdims=True)

#     output = np.dot(weights,V)

#     return np.round(output,4)


In [ ]:
# calculateAttentionWeights()
# selfAttentionOutput()

array([[0.5028, 1.    ],
       [0.3759, 1.1276],
       [0.502 , 1.146 ]])

In [ ]:
# import numpy as np

# HEAD1_WEIGHTS = np.array([0.6, 0.4], dtype=np.float64)
# HEAD1_VALUES = np.array([
#     [1.0, 0.0],
#     [0.0, 2.0]
# ], dtype=np.float64)

# HEAD2_WEIGHTS = np.array([0.3, 0.7], dtype=np.float64)
# HEAD2_VALUES = np.array([
#     [2.0, 1.0],
#     [-1.0, 3.0]
# ], dtype=np.float64)

# OUTPUT_PROJECTION = np.array([
#     [1.0, 0.5, -1.0, 0.0],
#     [0.0, 1.0, 0.5, -0.5]
# ], dtype=np.float64)

# OUTPUT_BIAS = np.array([0.1, -0.2], dtype=np.float64)


# def headOneOutput():
#     output = np.dot(HEAD1_WEIGHTS,HEAD1_VALUES)
#     return np.round(output,4)

# def headTwoOutput():
#     output = np.dot(HEAD2_WEIGHTS,HEAD2_VALUES)
#     return np.round(output,4)

# def concatenateHeads():
#     head1 = headOneOutput()
#     head2 = headTwoOutput()
#     concatenate = np.concatenate((head1,head2))
#     return np.round(concatenate,4)

# def multiHeadOutput():
#     concatenate = concatenateHeads()
#     output = np.dot(OUTPUT_PROJECTION,concatenate)+OUTPUT_BIAS
#     return np.round(output,4)


In [ ]:
# headOneOutput()
# headTwoOutput()
# concatenateHeads()
# multiHeadOutput()


array([ 1.2 , -0.65])

In [ ]:
# import numpy as np

# TOKEN_EMBEDDINGS = np.array([
#     [0.1,  0.2, 0.3,  0.4],
#     [0.5,  0.4, 0.3,  0.2],
#     [0.0, -0.1, 0.2, -0.2]
# ], dtype=np.float64)

# POSITIONAL_ENCODINGS = np.array([
#     [0.0, 1.0, 0.0, 1.0],
#     [0.5, 0.5, 0.5, 0.5],
#     [1.0, 0.0, 1.0, 0.0]
# ], dtype=np.float64)

# D_MODEL = 4

# def transformerDimensions():
#     sequence_length = TOKEN_EMBEDDINGS.shape[0]
#     emb_dim = TOKEN_EMBEDDINGS.shape[1]
#     scaled_factor = np.sqrt(D_MODEL)

#     return(
#         int(np.round(sequence_length,4)),
#         int(np.round(emb_dim,4)),
#         float(np.round(scaled_factor,4))
#     )

# def scaleTokenEmbeddings():
#     scaled = TOKEN_EMBEDDINGS*np.sqrt(D_MODEL)
#     return np.round(scaled,4)

# def addPositionalEncoding():
#     scaled = scaleTokenEmbeddings()
#     encoded = scaled+POSITIONAL_ENCODINGS
#     return np.round(encoded,4)

# def transformerInputSummary():
#     encoded = addPositionalEncoding()
#     sequence_mean = np.mean(encoded,axis=0)
#     return np.round(sequence_mean,4)

In [ ]:
# transformerDimensions()
# scaleTokenEmbeddings()
# addPositionalEncoding()
# transformerInputSummary()

array([0.9   , 0.8333, 1.0333, 0.7667])

In [284]:
import numpy as np

X = np.array([1.5, -0.5], dtype=np.float64)
Y = np.array([1.0, 0.0], dtype=np.float64)
LEARNING_RATE = 0.1

W = np.array([
    [0.2, -0.4],
    [0.7,  0.1]
], dtype=np.float64)

B = np.array([0.1, -0.2], dtype=np.float64)

def forwardDense():
    z = np.dot(W,X)+B
    prediction = 1/(1+np.exp(-z))
    return np.round(z,4) , np.round(prediction,4)

def calculateDenseLoss():
    z,prediction = forwardDense()
    loss = -np.mean(Y*np.log(prediction)+(1-Y)*np.log(1-prediction))
    return float(np.round(loss,4))

def backwardDense():
    z,prediction = forwardDense()
    dz = (prediction-Y)/len(Y)
    dw = np.outer(dz,X)
    db = dz
    return np.round(dw,4) , np.round(db,4)

def trainDenseOneStep():
    z , prediction = forwardDense()
    loss_before = calculateDenseLoss()
    dw , db = backwardDense()
    updated_w = W-LEARNING_RATE*dw
    updated_b = B-LEARNING_RATE*db
    z_new = np.dot(updated_w,X)+updated_b
    pred_new = 1/(1+np.exp(-z_new))

    loss_after = -np.mean(Y*np.log(pred_new)+(1-Y)*np.log(1-pred_new))
    return (
        np.round(updated_w,4),
        np.round(updated_b,4),
        np.round(loss_before,4),
        np.round(loss_after,4)
    )

In [285]:
forwardDense()
calculateDenseLoss()
backwardDense()
trainDenseOneStep()

(array([[ 0.2266, -0.4089],
        [ 0.6482,  0.1172]]),
 array([ 0.1177, -0.2345]),
 np.float64(0.8043),
 np.float64(0.7527))